### ISSUE TITLE
Upload: extension.type is empty or was not found in payload

### ISSUE THREAD

**Issue by JGeerWM** [Developer-Autodesk/data.management.api-nodejs-sample#1]
It looks like the storageSpecData function in dm.js may be missing required information.  I am trying to run the example and the response from '/data/v1/projects/ + projectId + '/storage' in dm.jst uploadFile()fails with the message:

> One or more input values in the request were bad","detail":"\"extension.type\" is empty or was not found in payload.

Looking at the schema found in the documentation https://developer.autodesk.com/en/docs/data/v2/tutorials/upload-file/, extension.type is mentioned. 

I'm trying to format the json returned from storageSpecData to work.  If I come up with an answer I will post it.

I also copied the json schema from the documentation site into http://jsonschemalint.com/draft5/#.  It looks like the example below the schema fails as well.

**Comment by augustogoncalves** [comment]
@JGeerWM thanks, fixed now.

Also take a look at the forge-data-management NPM

**Comment by JGeerWM** [comment]
Very nice!  thank you @augustogoncalves
